### ISSUE TITLE
Package 'emacs-25.0' is unavailable

### ISSUE THREAD

**Issue by mtgred** [Kungsgeten/netrunner#4]
When trying to install the package from MELPA.

**Comment by Kungsgeten** [comment]
Which version of Emacs do you have? You can find out by running `M-x emacs-version`. The `netrunner` packages requires Emacs 25, because of some new code there which made it more comfortable to write. I may rewrite it and make it possible to run under Emacs 24 if I find the time.

**Comment by mtgred** [comment]
`24.5.1`

I'm happy to upgrade to Emacs 25 when it's available on Mac OS.

In the meantime i'm stuck to this version: https://emacsformacosx.com/

**Comment by Kungsgeten** [comment]
There are Emacs 25 versions available there: https://emacsformacosx.com/builds

Anyway, I've updated the code now so it should work with Emacs 24. Please try it out :)
